#!/bin/bash

# ==============================================================================
# BOOTSTRAP PHASE 5 — HARDWARE FINGERPRINT
# ==============================================================================
# Records a hardware-facts YAML snapshot (hostname, hardware label, OS, arch,
# target network config, SSH key) and an Ansible inventory stub under
# ansible/archive/ — read-only inputs, no changes to the node itself.
#
# Invoked by scripts/bootstrap.sh as part of a normal (non `--network-only`)
# run, right after Phase 4 in the same process's already-collected network
# config. Also fully self-contained — if nothing saved a NETWORK_STATE_FILE
# yet, this prompts for the target static IP/prefix/gateway/DNS itself
# (same as bootstrap.sh's own preamble):
#   bash scripts/phases/bootstrap/05-hardware-fingerprint.sh
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../lib/common.sh
source "${SCRIPT_DIR}/../../lib/common.sh"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

VERSION="4.3.0"
HOSTNAME="homelab-control-plane"
SSH_KEY="$HOME/.ssh/id_ed25519"
TIMESTAMP=$(date +%Y%m%dT%H%M%S)
TARGET_USER="${TARGET_USER:-${SUDO_USER:-$USER}}"
NETWORK_STATE_FILE="${REPO_ROOT}/ansible/archive/outputs/.bootstrap-network-state"

detect_docker_repo_os   # side effect: sources /etc/os-release, sets PRETTY_NAME
detect_static_iface
detect_hardware_label

header "[PHASE 5] Hardware Fingerprint"

# Always reuse a complete, already-collected answer (from bootstrap.sh's own
# preamble moments ago, or an earlier standalone phase run) — only prompts
# when there's genuinely nothing to reuse.
NETWORK_REUSE_IF_COMPLETE=true
collect_network_config "$NETWORK_STATE_FILE"

FACTS_DIR="${REPO_ROOT}/ansible/archive/outputs"
FACTS_FILE="${FACTS_DIR}/hardware-facts-${HOSTNAME}-${TIMESTAMP}.yml"
mkdir -p "$FACTS_DIR"

# Joined (not trailing-newline-terminated) so it drops into the heredoc as
# its own line(s) without producing a blank line before the next key.
DNS_YAML_LIST=""
IFS=',' read -ra _dns_facts <<< "$TARGET_DNS"
for _dns_entry in "${_dns_facts[@]}"; do
    if [ -n "$DNS_YAML_LIST" ]; then
        DNS_YAML_LIST="${DNS_YAML_LIST}"$'\n'"  - ${_dns_entry}"
    else
        DNS_YAML_LIST="  - ${_dns_entry}"
    fi
done

cat > "$FACTS_FILE" << YAML
---
# Hardware facts — generated by bootstrap.sh v${VERSION}
# $(date -u +"%Y-%m-%d %H:%M:%S UTC")

hostname: ${HOSTNAME}
role: control-plane
hardware: ${HARDWARE_LABEL}
os: ${PRETTY_NAME}
arch: $(uname -m)
target_ip: ${TARGET_IP}
prefix: ${TARGET_PREFIX}
gateway: ${TARGET_GATEWAY}
dns:
${DNS_YAML_LIST}
interface: ${STATIC_IFACE}
ssh_key: ${SSH_KEY}.pub
bootstrapped_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
bootstrap_version: ${VERSION}
YAML

info "Hardware facts saved: ${FACTS_FILE}"

# Inventory stub
INVENTORY_DIR="${REPO_ROOT}/ansible/archive/inventory"
mkdir -p "$INVENTORY_DIR"
INVENTORY_FILE="${INVENTORY_DIR}/discovered-hosts.yml"

if ! grep -q "$HOSTNAME" "$INVENTORY_FILE" 2>/dev/null; then
    cat >> "$INVENTORY_FILE" << YAML

# Added by bootstrap.sh — $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# OOBE step 7 (oobe_setup_ansible) will write the full ansible.cfg + inventory
all:
  hosts:
    ${HOSTNAME}:
      ansible_host: ${TARGET_IP}
      ansible_user: ${TARGET_USER}
      role: control-plane
YAML
    info "Inventory stub written: ${INVENTORY_FILE}"
else
    info "Inventory stub already contains ${HOSTNAME} — skipped"
fi
